"""add sandboxes and sandbox_emails tables

Revision ID: 5e03969e7e96
Revises: 
Create Date: 2026-05-13 23:48:36.300626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e03969e7e96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mock_endpoints', 'is_immutable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('workspaces', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('workspaces_smtp_username_key', 'workspaces', type_='unique')
    op.create_index(op.f('ix_workspaces_api_key'), 'workspaces', ['api_key'], unique=True)
    op.create_index(op.f('ix_workspaces_smtp_username'), 'workspaces', ['smtp_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_smtp_username'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_api_key'), table_name='workspaces')
    op.create_unique_constraint('workspaces_smtp_username_key', 'workspaces', ['smtp_username'])
    op.alter_column('workspaces', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('mock_endpoints', 'is_immutable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
